### ISSUE TITLE
where is GoogleDocs Arduino example?

### ISSUE THREAD

**Issue by Santosh1971** [electronicsguy/ESP8266#1]
where is GoogleDocs Arduino example which you are asking to refer? there are so many in google search

**Comment by electronicsguy** [comment]
It's my my repo itself. [HTTPSRedirect](https://github.com/electronicsguy/ESP8266/tree/master/HTTPSRedirect). Check the _.ino_ file there. Let me know if you have any questions.

**Comment by Santosh1971** [comment]
Thanks Sujay for your response.
I have followuing querries
1. How to resolve certificate mismatch?
2. Can I have my own google spreadsheet which I can update and read back.?
which folder and what name I have to give to that spreadsheet.

followings are the serial data I received when I am running your program


...
WiFi connected
IP address:
192.168.0.56
Connecting to script.google.com
Certificate mis-match
2b

Successfully wrote: Hello
into spreadsheet.

0



==============================================================================
125


Event Title, Description, Recurring?, All-day?, First Reminder (in minutes
before event)
Send emails, Need to send important emails, true, true, 900
Buy dress, Need to buy daughter's dress, true, true, 600
Get car serviced, Need to get my car checked and oil filter replaced, true,
true, 720


==============================================================================
5

Hello

0


Pl. advise!


Thanks
Santosh
Bangalore
8197239206



On Sat, May 7, 2016 at 12:40 AM, Sujay Phadke <notifications@github.com>
wrote:

> It's my my repo itself. HTTPSRedirect
> <https://github.com/electronicsguy/ESP8266/tree/master/HTTPSRedirect>.
> Check the *.ino* file there. Let me know if you have any questions.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/electronicsguy/ESP8266/issues/1#issuecomment-217532862>
>



-- 
Thanks and Regards,
Santosh Jha
8197239206

**Comment by Santosh1971** [comment]
what is
*GScriptId = "AKfycbzYw5G-oxvnwHpAJfDsS0PWNrO0KTBMiCW78lHUcEO6ZnFHvSw";

how to get it?

On Sat, May 7, 2016 at 8:36 AM, Santosh Kr. jha <jha.santosh.kr@gmail.com>
wrote:

> Thanks Sujay for your response.
> I have followuing querries
> 1. How to resolve certificate mismatch?
> 2. Can I have my own google spreadsheet which I can update and read back.?
> which folder and what name I have to give to that spreadsheet.
>
> followings are the serial data I received when I am running your program
>
>
> ...
> WiFi connected
> IP address:
> 192.168.0.56
> Connecting to script.google.com
> Certificate mis-match
> 2b
>
> Successfully wrote: Hello
> into spreadsheet.
>
> 0
>
>
>
>
> ==============================================================================
> 125
>
>
> Event Title, Description, Recurring?, All-day?, First Reminder (in
> minutes before event)
> Send emails, Need to send important emails, true, true, 900
> Buy dress, Need to buy daughter's dress, true, true, 600
> Get car serviced, Need to get my car checked and oil filter replaced,
> true, true, 720
>
>
>
> ==============================================================================
> 5
>
> Hello
>
> 0
>
>
> Pl. advise!
>
>
> Thanks
> Santosh
> Bangalore
> 8197239206
>
>
>
> On Sat, May 7, 2016 at 12:40 AM, Sujay Phadke <notifications@github.com>
> wrote:
>
>> It's my my repo itself. HTTPSRedirect
>> <https://github.com/electronicsguy/ESP8266/tree/master/HTTPSRedirect>.
>> Check the *.ino* file there. Let me know if you have any questions.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/electronicsguy/ESP8266/issues/1#issuecomment-217532862>
>>
>
>
>
> --
> Thanks and Regards,
> Santosh Jha
> 8197239206
>



-- 
Thanks and Regards,
Santosh Jha
8197239206

**Comment by electronicsguy** [comment]
@Santosh1971   ok so it's working for you. Regarding your other questions, you need to read up on your own and learn the basics since I cannot explain all those details here. 

FYI: certificate mismatch is a security feature but everything will still run fine with it.  I think the "script.google.com" domain internally redirects to different servers based on geographic location, or some other parameter, which is why you're getting a mismatch. You can use the openssl s_client to generate your own certificate as described here: [get remote cert](http://stackoverflow.com/questions/7885785/using-openssl-to-get-the-certificate-from-a-server).

You should read up about Google Apps Script and how to create your own script. A good starting point is here: [apps-script-tutorials](https://developers.google.com/apps-script/articles). Then you'll know how to create a script for your own spreadsheet and how to extract the script Id.  There's a learning curve but once you're past it, it's a lot of fun. Most of it is based on Javascript syntax.

**Comment by Santosh1971** [comment]
Thanks for the explanation Sujay.
Its working but it is not writing in my file... and the file you have
pointed is read only for me..so unable to use it.

On Sun, May 8, 2016 at 8:44 AM, Sujay Phadke <notifications@github.com>
wrote:

> @Santosh1971 <https://github.com/Santosh1971> ok so it's working for you.
> Regarding your other questions, you need to read up on your own and learn
> the basics since I cannot explain all those details here.
>
> FYI: certificate mismatch is a security feature but everything will still
> run fine with it. I think the "script.google.com" domain internally
> redirects to different servers based on geographic location, or some other
> parameter, which is why you're getting a mismatch. You can use the openssl
> s_client to generate your own certificate as described here: get remote
> cert
> <http://stackoverflow.com/questions/7885785/using-openssl-to-get-the-certificate-from-a-server>
> .
>
> You should read up about Google Apps Script and how to create your own
> script. A good starting point is here: apps-script-tutorials
> <https://developers.google.com/apps-script/articles>. Then you'll know
> how to create a script for your own spreadsheet and how to extract the
> script Id. There's a learning curve but once you're past it, it's a lot of
> fun. Most of it is based on Javascript syntax.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/electronicsguy/ESP8266/issues/1#issuecomment-217688341>
>



-- 
Thanks and Regards,
Santosh Jha
8197239206

**Comment by electronicsguy** [comment]
@Santosh1971   Correct. If you want to write to you own file, you'll have to create your own spreadsheet with the script and change the appropriate parameters. Please read up on how to use Google Apps script and you'll understand.
