### ISSUE TITLE
Google replies 404 

### ISSUE THREAD

**Issue by wilda17** [electronicsguy/ESP8266#2]
Hi,
first of all I want to say thank you - I think the code works ;)

But there is an issue - all requests are aborted by google (Error 404 (Not Found))

I found out if you take instead of script.google.com - www.script.google.com the connection works. If i take the url without the www at the beginning the connection doesn't work.

Do you have an idea what the problem could be?
Thank you for your help 

![error](https://cloud.githubusercontent.com/assets/19578925/15781772/f5be039e-29a7-11e6-9b42-6bee83a3ac71.png)

**Comment by electronicsguy** [comment]
@wilda17   I don't know why you're seeing this error. It should work with "script.google.com" using SSL, since that's what Google uses and that's what they mention on the website. Could you try using it directly through your browser and see if it work? Try pasting the entire URL into your browser (like https://script.google.com/.....) and see what happens.

**Comment by wilda17** [comment]
If i try it without www it doesn't even connect. The URL is correct and works properly if I try to use it in my browser or try to send the GET request manually.

**Comment by electronicsguy** [comment]
I'm afraid I cannot reproduce the bug so I cannot provide any pointers on how to solve it. My suggestion is to tweak network settings, another wifi network, DNS, etc. and see if it works.

**Comment by wilda17** [comment]
wow! I don't really know what happend - but now it works. I want to read calendar entries to an array. The function client.printRedir just prints the output to the serial terminal - do you have an idea how i can get this values to an array?

**Comment by electronicsguy** [comment]
You can use standard C or C++ syntax for this. Use a for loop and write the fetched values into the array.
