### ISSUE TITLE
Example for append date and time in google sheet using version 2.1 of httpsredirect

### ISSUE THREAD

**Issue by awaisnajam** [electronicsguy/ESP8266#35]
Hi Sujay,

Can you please add an example of append date and time in google sheet with different GMT settings using version 2.1 of httpsredirect?

Thanking you in advance.

Regards,
Awais

**Comment by electronicsguy** [comment]
Hi,
      You can do that easily at the application layer. Collect the current date time, convert it into a string and use that as the payload to write to a row using the example.

This link will explain how to get date/time on esp8266: [date-time](http://www.esp8266.com/viewtopic.php?f=19&t=8916)
