### ISSUE TITLE
Asking for phantom library?

### ISSUE THREAD

**Issue by soopirV** [electronicsguy/ESP8266#37]
I'm very new to this, but when I try to use this library, I get a compile error stating that <WiFiSecureClient.h> is missing.  I was confused because I didn't call for that library, but now see that it's #include in the <HTTPSredirect.h> library.  I can't locate this library, and am not sure what to do.  

Here is the error I receive:
`In file included from C:\Arduino\libraries\HTTPSRedirect/HTTPSRedirect.h:7:0,
                 from Waste_Pump_scanner_esp8266_v1.ino.ino:3:
C:\Arduino\libraries\HTTPSRedirect/WiFiClientSecure.h:25:24: fatal error: WiFiClient.h: No such file or directory
 #include "WiFiClient.h"
                        ^
compilation terminated.`

**Comment by electronicsguy** [comment]
Hi, 
    Have you made any changes? The correct name of the included library is: "WiFiClientSecure.h", from the file: "HTTPSRedirect.h". This is a required file and should be there in your system if you've installed the esp8266 core for Arduino correctly. Is any other esp8266 wifi example working for you?

Please mention your specs clearly: OS platform, Arduino ver, esp8266 core version, HTTPSRedirect version. 

Please attach the exact error message you get here.

**Comment by soopirV** [comment]
Sorry, I have typed it incorrectly!  It was looking for "WiFiClientSecure.h", not the way I typed it.  I have successfully used ESP8266 to write to ThingSpeak, and followed an early tutorial enabling me to control an LED with a webpage, but will try to reinstall the ESP8266 core.  
I'm using Win7, Arduino IDE 1.6.5, and am using a nodeMCU-type device.

**Comment by soopirV** [comment]
I started over- upgraded to 1.8.2, verified that ESP8266 core was deployed correctly, and then re-did the code.  No errors...not sure what is different, maybe a small character issue somewhere!  Thanks for the assist regardless!

**Comment by electronicsguy** [comment]
:+1: good luck. let me know if you have any more trouble with it.
