### ISSUE TITLE
Sketch not working on SDK 2.4.0-rc1

### ISSUE THREAD

**Issue by capedra** [electronicsguy/ESP8266#38]
Opened an issue on https://github.com/esp8266/Arduino/issues/3330

SSL handshake not returning OK for the host script.googleusercontent.com.

**Comment by electronicsguy** [comment]
Have you made any changes to the sample sketch? Could you upload it (a minimal verifiable example) somewhere so others could reproduce the problem? Thanks.

**Comment by capedra** [comment]
@electronicsguy 
Hello, I'm really sorry that I was in a rush yesterday but I replied to you and to Ivan there on the mentioned link:

I think this is the main problem that's been happening only on 2.4.0 RC1:
```
Alert: decode error
Error: SSL error 50
:wr 7 7 0
:wrc 7 7 0
Alert::rcl
:abort
 unexpected message
Alert: close notify
```

**Comment by electronicsguy** [comment]
fixed: [3330]https://github.com/esp8266/Arduino/issues/3330#issuecomment-306379837l)
