### ISSUE TITLE
Arduino Nano Communication with ESP8266-1

### ISSUE THREAD

**Issue by DKAagri** [electronicsguy/ESP8266#39]
I am using arduino nano board with ESP8266-1 wifi module .. and i am getting error  "fatal error: ESP8266WiFi.h: No such file or directory" . 
This project is running with node MUC ESP8266  module but i want to run this project with nano with ESP8266-1 module as shown in your video .. my aim is to read arduino nano three ADC value and upload over google sheet .

**Comment by electronicsguy** [comment]
1. You don't need an Arduino with ESP8266. ESP8266 is a complete SoC in itself, and you can directly program it through Arduino IDE if you wish. Any reason why you're using Arduino nano? Please use only ESP8266 to begin with.

2. If you install the ESP8266 library within Arduino, it'll install all relevant files including the file in question (ESP8266WiFi.h). So either you've not installed the esp8266 library, or there is some problem with your configuration. Please confirm what it is.

3. The video is not mine, somelse made it, for the older version. Please use only version 2+.

**Comment by DKAagri** [comment]
Actually i have to read  6 ADC values and upload on google sheet . ESP 8266 doesn't have that much adc pin becoz of that i choose nano board . i though i will read all value from nano pin and transfer through ESP8266 wifi module .

**Comment by electronicsguy** [comment]
Then check your esp8266 library install. The file you've mentioned is part of that.

**Comment by DKAagri** [comment]
thanks for your support and valuable knowledge ..   last thing i want know - how to program/ flash same code (googleDocs.ino) in ESP8266-1 by using nano or uno. i don't know how to deal with this problem. every time i am  getting fatal error: ESP8266WiFi.h: No such file or directory . i think ESP8266-1 should be in debug mode by connecting GP0 pin to ground .but i don't know which board i have to select to dump the code

**Comment by electronicsguy** [comment]
As already mentioned, please do not use arduino to program ESP8266. Please read up (google it) how to program an ESP8266 directly. It's pretty straightforward, but I can't go into the details here. 

Please go thru the link I mentioned above. If you have a basic understanding of embedded systems, it should be straightforward to install the esp8266 library. The file is part of that library, and not part of this project.
