### ISSUE TITLE
ESP32 Not working

### ISSUE THREAD

**Issue by Corvek** [electronicsguy/ESP8266#42]
Awesome code. Was able to get everything up and running on ESP8266, but have had zero luck with ESP32.  Has anyone had success that would be willing to post their sketch? I replaced the include ESP8266WiFi.h with WiFi.h, the compile first complains at there being no client->verify...if I comment that code out, my void loop() basically seems to hang....thought or ideas?

**Comment by electronicsguy** [comment]
Hi, 
      Sorry to know. Yes I'm working on the esp32 support. There are still some problems with the upstream ssl library included as part of esp32 SDK, so need to figure out how to work around that. Will keep you posted here.

**Comment by Corvek** [comment]
Thanks for the reply. Good to know it was not just a me thing! Hahaha.
Have a great day!

**Comment by sj3995** [comment]
Thank you very much for your sharing. I'm also having difficulties with ESP32. For the sensor data posting example working with your code (http://embedded-lab.com/blog/post-data-google-sheets-using-esp8266/), ESP8266 works fine but ESP32 closes the connection after several posting, giving an error message: [ssl_client.cpp:25] handle_error(): SSL-An invalid SSL record received 

I'm new to this kind of IoT works so it's very difficult to figure this out .. really appreciate it if you could give any updates, thanks!

**Comment by zenmanenergy** [comment]
Has there been any update on this? If not, I'll throw my hat into the ring

**Comment by electronicsguy** [comment]
@sj3995   ESP32 won't work for now. There have to be many changes made for it to be compatible with the upstream SSL library. Last I had checked, they were still working on making the SSL library stable. It'll take another few months for me to work on it. If someone has already got it working reliably, by all means make a pull request,

**Comment by SensorsIot** [comment]
Any news about the ESP32?

**Comment by electronicsguy** [comment]
@SensorsIot   Sorry for the delay. Things have been held up from my side now due to many constraints. Simple answer is no, not as yet.

**Comment by epicface2304** [comment]
Sorry to bring an old thread from the dead, but is the ESP32 compatible now? My ESP32 freezes when connecting to script.google.com
