### ISSUE TITLE
How to save A1 in variable???

### ISSUE THREAD

**Issue by mechanic98** [electronicsguy/ESP8266#43]
hi,
i want to save A1 that read from sheet in the variable
EX:
String S1=A1(that read from sheet...)

 Serial.println(F("GET Data from cell 'A1':"));
  if (client->GET(url3, host)){
    ++connect_count;
  }

**Comment by electronicsguy** [comment]
at the moment, you cannot. Will be releasing a new library soon which will make this possible, along with a bunch of other improvements.

**Comment by mechanic98** [comment]
can you see this url and help to me?

**Comment by mechanic98** [comment]
can you see this url and help to me?
https://github.com/JhonControl/ESP8266_GPIO_GoogleSpreadsheet/issues/1

**Comment by lorol** [comment]
@mechanic98 
Meanwhile (until the author releases nice new version) you can check my workaround here:
https://github.com/lorol/Googlesheet_DHT_simple

**Comment by mechanic98** [comment]
hi
thanks for reply. 🙏
your code is very good.
but i give error whet code go to "Write to GS"
this is my serial monitor :
https://pastebin.com/rVXux49i

this is my google sheet adress:
https://docs.google.com/spreadsheets/d/1fKZXZ2m-wa9sV9OcCZ9AFa3THpvaPREM8k_mcU--NM4/

thanks a lot

**Comment by mechanic98** [comment]
hi 
I give now only an error:

------S: 60
E: 0
C: 7
T: 23.50
H: 23.90
I: 192.168.1.2
-------------------------
Write to GS
{"result":"error","error":{"message":"Invalid argument: id","name":"Exception","fileName":"Code (DHT11)","lineNumber":41,"stack":"\tat Code (DHT11):41 (handleResponse)\n\tat Code (DHT11):24 (doGet)\n"}}

**Comment by mechanic98** [comment]
wow its work  !!!!! 
i am so hapyy :dancing_men: 
i change this:
var doc = SpreadsheetApp.openById(SCRIPT_PROP.getProperty("key"));
to:
var ss = SpreadsheetApp.openById('19L6_RAxkS3tihfcW_TwHuKAusHXCiEwJOECiNuYD-d0');
and program run without any error :D

**Comment by JhonControl** [comment]
Excellent implementation of @lorol . 
perfect @mechanic98 , you have solved the problem and have created your application.

regards
