### ISSUE TITLE
Storing output of client->GET(url, host) to String

### ISSUE THREAD

**Issue by bigFin** [electronicsguy/ESP8266#45]
When client->GET(url, host) is invoked, the value from the spreadsheet is printed directly to the serial monitor. I would like to store this value in a String. How do i do it?

**Comment by electronicsguy** [comment]
@bigFin  as of now, you cannoy. it's on my list :) new job has taken up all the time, but 90% of a new project is ready, which will support this and a whole lot more. please stay tuned. Hopefully another 2-3 weeks.

**Comment by bigFin** [comment]
Heyo @electronicsguy, thanks for the prompt reply. Can you suggest a workaround for the time being? I suspect that there's a Serial.println() in the client GET method that could be replaced with a return. I'm going to go hunting for that now, but if you can point me in the right direction I'd appreciate it. 

Otherwise, good luck with the new job and the new project! Thanks for your contributions to the digiverse.

**Comment by bigFin** [comment]
Wowza I should really read the documentation more thoroughly. I found this little gem `getResponseBody();` and then used `String str = client->getResponseBody();` to get wrangle it into a string.  A minor bug is that this causes the response to print to the serial monitor despite the fact that the option `client->setPrintResponseBody(false);` is false...

**Comment by electronicsguy** [comment]
@bigFin   thanks for reporting it. I did have that function, but it was only used for testing. You can use it for now. It'll be corrected and more flexible methods will be added in the next version. 

cheers.

**Comment by tlujan0001** [comment]
Hi @electronicsguy, thank you for you contribution.  I'm a beginner and have learned so much using this library.  I too am trying to to pass the output to a string, @bigFin could you possibly share the code you used for your work around?  I'm so new I don't even know where to paste "String str = client->getResponseBody();".

**Comment by bigFin** [comment]
Hey @tlujan0001 
You can use the function `getResponseBody();` and then `String str = client->getResponseBody();` in your main loop. Just be sure to call getResponseBody() before pointing a string to it. After this your output will be stored in the string str.

**Comment by tlujan0001** [comment]
@bigFin  I got it! Thank you for the clarification.  It works great, except I'm seeing two additional strange characters after the string on my LCD.  Have you experienced this?

**Comment by electronicsguy** [comment]
@tlujan0001  what characters are they? print int(c) to find out the ascii value.

**Comment by bigFin** [comment]
@tlujan0001 Nope it works as expected. Sounds like you've other fish to fry!

**Comment by tlujan0001** [comment]
Hey guys, looks like the characters I was seeing on the LCD came from a return after printing my string.  I added trim(); to fix this: 
`String str= client->getResponseBody();
   str.trim();`
