### ISSUE TITLE
openssl command

### ISSUE THREAD

**Issue by zenmanenergy** [electronicsguy/ESP8266#47]
this is super minor...
I don't know if this is specific to a mac's command line, but when I run this:

echo | openssl s_client -connect script.google.com:443 | openssl x509 -fingerprint -noout

I get an error:
-bash: syntax error near unexpected token `&'

removing the & fixes it.
echo | openssl s_client -connect script.google.com:443 | openssl x509 -fingerprint -noout

**Comment by electronicsguy** [comment]
@zenmanenergy already documented in Readme's Sec. III(d) under "Note". Are you talking about anything else?
