### ISSUE TITLE
How to post data to a specific row??

### ISSUE THREAD

**Issue by w1ndsper** [electronicsguy/ESP8266#51]
Hi there, I want to know instead of using appendrow to post the data, is there anyway to post data to a specific row in google spreadsheet??

**Comment by electronicsguy** [comment]
@w1ndsper   will update you soon regarding this. a new project is currently under test which will do this and much more. My new job since last few months has been taking up a lot of my time to work on indie projects. 

Hopefully in a few weeks time :)

**Comment by bigFin** [comment]
Yeah, use `spreadsheets.values.update(A1)` to write stuff into A1. Source: developers.google.com/sheets/api/guides/values

**Comment by bigFin** [comment]
Yeah, use setValue().

`Sheet.getRange('A1').setValue('doge is good');`
