### ISSUE TITLE
failed to send data using esp8266

### ISSUE THREAD

**Issue by amirzahidin** [electronicsguy/ESP8266#52]
this is my code:
`

//#include <HTTPSRedirect.h>

#include <ESP8266WiFi.h>
#include "HTTPSRedirect.h"
#include "DebugMacros.h"

const char* ssid = "****";        //put your router ssid
const char* password = "****";      // put your router password

//const char* ssid = "taufiq"; //put your router ssid
//const char* password = "iiiiiiii"; // put your router password

const char* GScriptId ="AKfycbxgbsdDgqguZVXKpyyO52_Pilfz-80gxZW4zpF_rm742McSDugf"; //your gscript id
const int dataPostDelay = 10000;
const char* host = "script.google.com";
const char* googleRedirHost ="script.googleusercontent.com";
const int httpsPort =443;
HTTPSRedirect client(httpsPort);
String url = String("/macros/s/") + GScriptId + "/exec?";
String data="";
String sensor1="";
String sensor2="";
String sensor3="";

void setup() {
  Serial.begin(9600);
  Serial.println("Connecting to wifi: ");
  Serial.println(ssid);
  Serial.flush();
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    }
  Serial.println(" IP address: ");
  Serial.println(WiFi.localIP());
  Serial.print(String("Connecting to "));
  Serial.println(host);
  bool flag = false;
  for (int i=0; i<5; i++){
    int retval = client.connect(host, httpsPort);
    if (retval == 1) {
      flag = true;
      break;
      }
      else
      Serial.println("Connection failed. Retrying…");
    }
  Serial.println("Connection Status: " + String(client.connected()));
  Serial.flush();
  if (!flag){
    Serial.print("Could not connect to server: ");
    Serial.println(host);
    Serial.println("Exiting…");
    Serial.flush();
    return;
    }
}

void postData(String sensor1, String sensor2, String sensor3){
  if (!client.connected()){
    Serial.println("Connecting to clientagain…");
    client.connect(host, httpsPort);
  }
  String urlFinal = url; 
          urlFinal += "sensor1="; 
          urlFinal += sensor1; 
          urlFinal += "&sensor2="; 
          urlFinal += sensor2 ;
          urlFinal += "&sensor3=" ;
          urlFinal += sensor3;
  Serial.println (urlFinal);
  client.printRedir(urlFinal,host,googleRedirHost);
  }
  
void loop() {
 
  if (Serial.available()){
    sensor1  = Serial.readStringUntil(',');
    Serial.read(); //next character is comma, so skip it using this
    sensor2 = Serial.readStringUntil(',');
    Serial.read();
    sensor3  = Serial.readStringUntil('\n');
     postData(sensor1, sensor2, sensor3);
    }
}

`

this is the error:
`
no matching function for call to 'HTTPSRedirect::printRedir(String&, const char*&, const char*&)'

`

can someone fix this problem?
i really appriciate it.

**Comment by electronicsguy** [comment]
You're using the older version of the library. Please use the latest version and go through the Readme and the example to see how to use it. There is no "printRedir" method anymore.
