### ISSUE TITLE
printRedir

### ISSUE THREAD

**Issue by JacquesBB** [electronicsguy/ESP8266#57]
Hello, 

I would like to praise this work, but have not yet been able to make it work. 

I am confused with HTTPSRedirect::printRedir, which gives me error in compilation with the latest version. 
Looking to the code, I see 

bool HTTPSRedirect::printRedir(void)

and actually, I have an error when in my code  I write 

client.printRedir(url, host, googleRedirHost);

as it is proposed in some examples. Searching on the Web, I see that there was another version with 

bool HTTPSRedirect::printRedir(const char* url, const char* host, const char* redirHost)

This library gives no errors, but still does not work with my code. What are the dirrerences in the versions, and which order should I use to post data from an ESP8266 to a googel sheet. 
I  ave verified that when I put in my browser "https://script.google.com"+url, 
I fill the proper google sheet  file, but I hnot yet been able to do it from the ESP8266.

Thanks for any hint.

**Comment by electronicsguy** [comment]
Hi,
  Please check the example requests within "GoogleDocs.ino". V2.0 of the library changed the way you access data, and you no longer use printRedir directly. The examples on the web are written by other people using V1.0 of the library, which is no longer supported.

**Comment by JacquesBB** [comment]
Thank you for your rapid answer, 

I have seen your example,  but was not able top make it work. his is why I went to see for other examples on the web, and then got more confused because of these difference of libraries. 

Now, looking back to your example, "GoogleDocs.ino" I find that  it would be extremely useful for all if you could provide an additional, much simpler example, with just a single logging order. It is difficult to see what is really needed for that, and what is superflous. 

For example, If I am now wrong now that 

```C++
// for stack analytics
extern "C" {
#include <cont.h>
  extern cont_t g_cont;
}
```
can be discarded. 
My  question is what would be the minimal code to  run 

https://script.google.com/macros/s/xxxxxxx/exec?pressure=1001.12&temperature=21&humidity=82&tempo=2&heater=1

which works well if I paste it in my browser ? 

Thanks
