### ISSUE TITLE
Ram usage - client connect

### ISSUE THREAD

**Issue by duarterr** [electronicsguy/ESP8266#59]
I have a fairly large project implemented with a nodeMCU. Now I want to log some data to a google spreadsheet using the library.

I'm having some trouble with the heap memory after calling "client->connect("script.google.com", 443)".
My device has about 17kB free at the moment of this call but apparently this is not enough and I get an memory exception and the device restarts...

With a simple sketch I'm able to use the library with no problems, but the connect call always consume about 18~19kB of free heap. Is this a known issue and how to avoid that?

**Comment by HuibGroenewegen** [comment]
I also had problems with the free heap memory and finally discovered that if you use the  V2.4.1 version of the ESP8266 board management definition library in Arduino ,the memory heap dissapears fast, but if you roll back to the V2.4.0 than it works ok even without a delay in the main loop.
May be this is your problem.

**Comment by duarterr** [comment]
Yes, I had already tried this and it reduces the memory consumption indeed. However, as I stated in the first post, I have a very large project and the ESP don't have enough heap to make a secure connection.

My solution is not elegant, but works...

I'm closing the issue as this is not a problem with the library.
