### ISSUE TITLE
ESP32 Compatibility

### ISSUE THREAD

**Issue by epicface2304** [electronicsguy/ESP8266#65]
Is the ESP32 compatible yet, because the README states: 
> A library for seamless data logging, communication and control for Internet of Things **(focus: ESP8266, ESP32)**

I've tried using the library with my ESP32, but it just freezes up when connecting.

**Comment by electronicsguy** [comment]
Yeah, sorry it's not compatible with esp32 as yet due to library issues.

**Comment by alonsoelectronica** [comment]
> Yeah, sorry it's not compatible with esp32 as yet due to library issues.

Oh my friend, I need this compatibility, I´ve lost all day for this jajaja I hope a solution ... meanwhile I try with this.
