### ISSUE TITLE
Question: Using HTTPSRedirect

### ISSUE THREAD

**Issue by ajsmcd** [electronicsguy/ESP8266#73]
Hello Sujay,

Thank you in advance for making HTTPSRedirect. It has helped me immensely with my projects when I need to interface with Google Sheets. I was wondering if it is possible to use this library with a Arduino Uno using  an Ethernet 2 (W5500) shield? I love using ESP8266 devices but have an application where I need to use an Ethernet connection but still require the use of the HTTPSRedirect functionality.

Regards,

Aaron

**Comment by electronicsguy** [comment]
Hey Aaron,
       I don't think that'll work, since HTTPSRedirect depends on the esp8266 wificlient library, BearSSL and other libraries. In fact, I don't think SSL is even possible on the Arduino. Plus you need a wifi connection.
