### ISSUE TITLE
esp32

### ISSUE THREAD

**Issue by supersjimmie** [electronicsguy/ESP8266#76]
I noticed that you do mention the esp32 in the readme.md. Because of several other reasons I need to step from esp8266 to esp32 and was very close to completing the "job" until I noticed that it doesn't work on my new esp32. Now I found in a closed issue you say it does not work on esp32 yet. 
Is there any news on that, or, could you advice some other way to get this working on an esp32?
I have a google calendar to control my central heating system (as a thermostat) and need to read my script-output from google to get the google calendar data into my esp...

**Comment by electronicsguy** [comment]
Hi @supersjimmie  Sorry, still no progress on that front unfortunately.
