### ISSUE TITLE
Connection to re-directed URL failed ..

### ISSUE THREAD

**Issue by 4inn** [electronicsguy/ESP8266#78]
Hello ! .. I have a question .. I am trying to use the new version of this library and it is giving me the following error "**Connection to re-directed URL failed!**" ..

I had already used another previous version a while ago and had no problems ..

But today trying to use it again with the new version gives me that error ..

This is all implemented and I log the data to the spreadsheet, but can not see the contents of cell A1 and neither the calendar information .. "**Error! Not connected to host.**"

I am using PlatformIO .. and the library of expressif8266 stage version ..

I also tried Arduino IDE and the library of esp8266 2.5.0 beta 3 and I do not care ...

Some help ? Any more information that may happen to you?

From already thank you very much !

**Comment by 4inn** [comment]
I'm sorry it's resolved ..

I leave it documented in case someone else happens ..

The error was when publishing the web application in the Google Scripts, it is important to establish a new version with a different number ..

Thank you ..

**Comment by 4inn** [comment]
The issue was resolved that he could not read the contents of cell A1 .. but the rest did not ..

```
Connecting to script.google.com
Certificate match.
Connection to re-directed URL failed!
Error! Not connected to host.

GET: Write into cell 'A1'
=========================
Error! Not connected to host.
Error! Not connected to host.

GET: Fetch Google Calendar Data:
================================
Error! Not connected to host.
Error! Not connected to host.
```

**Comment by electronicsguy** [comment]
Please use another wifi access, point, check permissions as described in the readme, and try another esp8266 board if you have one. 
If you still have the same problem, report back. I tried it today and it connects fine.

**Comment by 4inn** [comment]
Hello .. well I did the test that you comment .. use two different wifi access points and in both I get the same error ..

What other proof do you think it is convenient for me to try?

Do you want to send me some tried-and-true code to burn to my device esp8266?
