### ISSUE TITLE
document has moved temporarily

### ISSUE THREAD

**Issue by chuckmerja** [electronicsguy/ESP8266#79]
My main issue is that I get 4 or 5 posts, even though the document has moved. But then I get no more posts to the sheet until I reset the ESP.  The certicicate always mismatches, but it will log some data anyway.
I have an "update sheet" script that I can run from laptop and it updates just fine.
Here is some output from serial port...
thanks in advance...

Connecting to wifi: 
Merja2015
.... IP address: 
192.168.1.23
Connecting to script.google.com
Connection Status: 1
Certificate mis-match
tag =__SRMS0Temp = 0 HUM= 0 WaterPress=  1807 WaterHtFt=  1.00
262

<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A HREF="https://script.googleusercontent.com/macros/echo?user_content_key=**_this is about 100 characters long_**
urlFinal etal =
script.google.com
script.googleusercontent.com
/macros/s/**_MY SHEET_**/exec?&tag=__SRMS&temperature=0&humidity=0&WatPrs=1807&WatHtIn=14&WatHtFt=1.00
tag =__SRMS0Temp = 0 HUM= 0 WaterPress=  854 WaterHtFt=  0.00
Connecting to client again…
still trying
262

**Comment by chuckmerja** [comment]
Apparently, i need to find HTTPRedirect for ESP32.  If i go back to the 8266 my code works fine with this library.  What is the difference between ESP32 and ESP8266 with respect to redirect??

**Comment by electronicsguy** [comment]
@chuckmerja the SSL library wasn't stable last time I checked on esp32. Hence it used to give such random errors. I'll have to check what the state is now with the latest version of the library
