### ISSUE TITLE
Hello .. well I did the test that you comment .. use two different wifi access points and in both I get the same error ..

### ISSUE THREAD

**Issue by 4inn** [electronicsguy/ESP8266#80]
Hello .. well I did the test that you comment .. use two different wifi access points and in both I get the same error ..

What other proof do you think it is convenient for me to try?

Do you want to send me some tried-and-true code to burn to my device esp8266?

_Originally posted by @4inn in https://github.com/electronicsguy/ESP8266/issues/78#issuecomment-489463916_

**Comment by electronicsguy** [comment]
The example is tried and tested. There is something else wrong with your setup.
