### ISSUE TITLE
Core Version incompatibility

### ISSUE THREAD

**Issue by Luisiado** [electronicsguy/ESP8266#81]
Hello, thanks for your library.
Since I try to compile the example I have several problems with a class that doesnt (error mssg: 'class EspClass' has no member named 'getFreeContStack') exist in the last core version 2.5.2 of ESP8266. So has to be downloaded to 2.5.0. Just to publish it in the documentation and save time for the rest of the users.
With ESP32 I have not get to compile yet and I tried with all available core releases.
Regards

**Comment by electronicsguy** [comment]
You have some other problem. getFreeContStack() is present in v2.5.2 of esp8266 library. Check your library code.

**Comment by Luisiado** [comment]
But in ESP32 I can not use the v2.5.2 esp8266 core library
