### ISSUE TITLE
No project license

### ISSUE THREAD

**Issue by ZakCodes** [electronicsguy/ESP8266#86]
We would like to use some parts of your projects, but unfortunately there's no license on your project, so we don't know whether it is compatible with ours. If you need any help to choose a license, you can take a look at [this great site from GitHub](https://choosealicense.com/), [this more detailed one](https://tldrlegal.com/) or this [list of all the licenses approved by the open source initiative](https://opensource.org/licenses).

A license isn't only going to protect us, it's going to help you protect yourself too. Most licenses include a clause denying any liability from your part for the project not working as expected.

If you want your project to be used by as many people as possible, consider choosing a permissive license like the [MIT license](https://opensource.org/licenses/MIT). It pretty much allows anyone to do anything with your code, but they can't hold you liable for anything. It's also very short, about 170 words, and relatively easy to understand for anyone.

**Comment by electronicsguy** [comment]
Hi,
 The project is as-is. I don't promise anything so there's no question of liability. Use at your own risk. I'll consider some other licence in the future. For now it's as mentioned at the end in the Readme (free to play around, paid for larger projects. Depends on the size of your "we" and the # of devices.. If you want to discuss further, drop me a note.

**Comment by ZakCodes** [comment]
Alright, thanks a lot for the answer!
