### ISSUE TITLE
Can this be used with TinyGSM?

### ISSUE THREAD

**Issue by Conwon99** [electronicsguy/ESP8266#96]
Can this library be used with TinyGSM? I am trying to send data to google sheets via an ESP32 T-call SIM800L GPRS module and am wondering if the TinyGSM client can be used to connect to the APN and have the HTTPRedirect client connect to the server?

Thanks in advance.

**Comment by electronicsguy** [comment]
Please provide more details. What's the SDK used for TinyGSM? Is it compatible with esp8266?
